const productItems = [
  { name: 'Zeta Alanine', servings: 12 },
  { name: 'Vit E', servings: 0.05 },
  { name: 'Taurine', servings: 1 },
  { name: 'Caffeine', servings: 0.25 },
  { name: 'Vit A', servings: 0.05 },
  { name: 'Taurine', servings: 1 },
  { name: 'Caffeine', servings: 0.25 },
  { name: 'Vit C', servings: 0.05 },
  { name: 'Taurine', servings: 1 },
  { name: 'Caffeine', servings: 0.25 },
  { name: 'Carnitine Tartrate', servings: 0.25 },
  { name: 'Citric Acid', servings: 0.6 },
  { name: 'Flavour', servings: 0.15 },
  { name: 'Malto', servings: 0.5 },
  { name: 'Calcium Silicate', servings: 0.03 },
  { name: 'Silicon Dioxide', servings: 0.04 },
  { name: 'Sucralose', servings: 0.1 },
  { name: 'Ace K', servings: 0.05 },
  { name: 'Color', servings: 0.001 },
  { PackagingName: '19 oz Pet Black Bottle', },
  { PackagingName: '01 Silica (10gm)',  },
  { PackagingName: 'Scoop 7.5cc', },
  { PackagingName: '89mm Pole Cap',  },
  { PackagingName: 'Carton 19oz - 12pk',},
];

module.exports = {
  getProductItems: () => productItems,
};
